language: rust
cache: cargo

INSTALL_GECKODRIVER: &INSTALL_GECKODRIVER
  |
    curl --retry 5 -LO https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
    tar xf geckodriver-v0.21.0-linux64.tar.gz

INSTALL_CHROMEDRIVER: &INSTALL_CHROMEDRIVER
  |
    curl --retry 5 -LO https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
    unzip chromedriver_linux64.zip
    export CHROMEDRIVER_ARGS=--verbose

INSTALL_WASM_BINDGEN_CLI: &INSTALL_WASM_BINDGEN_CLI
  |
    cargo install wasm-bindgen-cli

matrix:
  include:
    - rust: nightly
      install: 
        - *INSTALL_GECKODRIVER
        - *INSTALL_CHROMEDRIVER
        - *INSTALL_WASM_BINDGEN_CLI

      script:
        - export RUST_LOG=wasm_bindgen_test_runner
        - cargo build --manifest-path Cargo.toml --target wasm32-unknown-unknown
        - CHROMEDRIVER=`pwd`/chromedriver cargo test --manifest-path Cargo.toml --target wasm32-unknown-unknown
        - GECKODRIVER=`pwd`/geckodriver cargo test --manifest-path Cargo.toml --target wasm32-unknown-unknown

      addons:
        firefox: latest
        chrome: stable

    - rust: nightly
      script:
        - cargo build --manifest-path Cargo.toml
        - cargo build --manifest-path codegen/Cargo.toml
        - cargo test --manifest-path Cargo.toml
        - cargo test --manifest-path codegen/Cargo.toml
