var N = null;var sourcesIndex = {};
sourcesIndex["cfg_if"] = {"name":"","dirs":[],"files":["lib.rs"]};
sourcesIndex["fnv"] = {"name":"","dirs":[],"files":["lib.rs"]};
sourcesIndex["heck"] = {"name":"","dirs":[],"files":["camel.rs","kebab.rs","lib.rs","mixed.rs","shouty_snake.rs","snake.rs","title.rs"]};
sourcesIndex["indexmap"] = {"name":"","dirs":[],"files":["equivalent.rs","lib.rs","macros.rs","map.rs","mutable_keys.rs","set.rs","util.rs"]};
sourcesIndex["js_sys"] = {"name":"","dirs":[],"files":["lib.rs"]};
sourcesIndex["lazy_static"] = {"name":"","dirs":[],"files":["inline_lazy.rs","lib.rs"]};
sourcesIndex["log"] = {"name":"","dirs":[],"files":["lib.rs","macros.rs"]};
sourcesIndex["proc_macro2"] = {"name":"","dirs":[],"files":["fallback.rs","lib.rs","strnom.rs","wrapper.rs"]};
sourcesIndex["quote"] = {"name":"","dirs":[],"files":["ext.rs","lib.rs","to_tokens.rs"]};
sourcesIndex["ruukh"] = {"name":"","dirs":[{"name":"vdom","dirs":[],"files":["conversions.rs","vcomponent.rs","velement.rs","vlist.rs","vtext.rs"]}],"files":["component.rs","dom.rs","lib.rs","vdom.rs"]};
sourcesIndex["ruukh_codegen"] = {"name":"","dirs":[{"name":"component","dirs":[{"name":"events","dirs":[],"files":["parser.rs"]}],"files":["events.rs","fields.rs","props.rs","state.rs"]},{"name":"html","dirs":[],"files":["element.rs","kw.rs"]}],"files":["component.rs","html.rs","lib.rs","suffix.rs"]};
sourcesIndex["syn"] = {"name":"","dirs":[{"name":"gen","dirs":[],"files":["gen_helper.rs","visit.rs"]}],"files":["attr.rs","buffer.rs","data.rs","derive.rs","error.rs","export.rs","expr.rs","ext.rs","file.rs","generics.rs","group.rs","ident.rs","item.rs","keyword.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","path.rs","print.rs","punctuated.rs","span.rs","spanned.rs","thread.rs","token.rs","tt.rs","ty.rs"]};
sourcesIndex["unicode_segmentation"] = {"name":"","dirs":[],"files":["grapheme.rs","lib.rs","tables.rs","word.rs"]};
sourcesIndex["unicode_xid"] = {"name":"","dirs":[],"files":["lib.rs","tables.rs"]};
sourcesIndex["wasm_bindgen"] = {"name":"","dirs":[{"name":"convert","dirs":[],"files":["closures.rs","impls.rs","mod.rs","slices.rs","traits.rs"]}],"files":["cast.rs","closure.rs","describe.rs","lib.rs"]};
sourcesIndex["wasm_bindgen_backend"] = {"name":"","dirs":[],"files":["ast.rs","codegen.rs","defined.rs","encode.rs","error.rs","lib.rs","util.rs"]};
sourcesIndex["wasm_bindgen_macro"] = {"name":"","dirs":[],"files":["lib.rs"]};
sourcesIndex["wasm_bindgen_macro_support"] = {"name":"","dirs":[],"files":["lib.rs","parser.rs"]};
sourcesIndex["wasm_bindgen_shared"] = {"name":"","dirs":[],"files":["lib.rs"]};
sourcesIndex["web_sys"] = {"name":"","dirs":[],"files":["lib.rs"]};
createSourceSidebar();
